version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: nutrihealth-db
    environment:
      POSTGRES_USER: nutrihealth
      POSTGRES_PASSWORD: nutrihealth
      POSTGRES_DB: nutrihealth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nutrihealth"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
